import type { BuiltinPresentationMeta } from "./types";

export const FALLBACK_BUILTIN_CATEGORY = "Other Built-ins" as const;

export const BUILTIN_PRESENTATION_META: Record<string, BuiltinPresentationMeta> = {
  "app.interrupt": { category: "Application", name: "Cancel / abort", order: 10 },
  "app.clear": { category: "Application", name: "Clear editor", order: 20 },
  "app.exit": { category: "Application", name: "Exit", order: 30 },
  "app.suspend": { category: "Application", name: "Suspend", order: 40 },
  "app.editor.external": { category: "Application", name: "Open external editor", order: 50 },
  "app.clipboard.pasteImage": { category: "Application", name: "Paste image from clipboard", order: 60 },

  "tui.input.newLine": { category: "Text Input", name: "Insert new line", order: 10 },
  "tui.input.submit": { category: "Text Input", name: "Submit input", order: 20 },
  "tui.input.tab": { category: "Text Input", name: "Tab / autocomplete", order: 30 },

  "tui.editor.cursorUp": { category: "Cursor", name: "Move cursor up", order: 10 },
  "tui.editor.cursorDown": { category: "Cursor", name: "Move cursor down", order: 20 },
  "tui.editor.cursorLeft": { category: "Cursor", name: "Move cursor left", order: 30 },
  "tui.editor.cursorRight": { category: "Cursor", name: "Move cursor right", order: 40 },
  "tui.editor.cursorWordLeft": { category: "Cursor", name: "Move cursor word left", order: 50 },
  "tui.editor.cursorWordRight": { category: "Cursor", name: "Move cursor word right", order: 60 },
  "tui.editor.cursorLineStart": { category: "Cursor", name: "Move to line start", order: 70 },
  "tui.editor.cursorLineEnd": { category: "Cursor", name: "Move to line end", order: 80 },
  "tui.editor.jumpForward": { category: "Cursor", name: "Jump forward to character", order: 90 },
  "tui.editor.jumpBackward": { category: "Cursor", name: "Jump backward to character", order: 100 },
  "tui.editor.pageUp": { category: "Cursor", name: "Scroll editor page up", order: 110 },
  "tui.editor.pageDown": { category: "Cursor", name: "Scroll editor page down", order: 120 },

  "tui.editor.deleteCharBackward": { category: "Deletion", name: "Delete character backward", order: 10 },
  "tui.editor.deleteCharForward": { category: "Deletion", name: "Delete character forward", order: 20 },
  "tui.editor.deleteWordBackward": { category: "Deletion", name: "Delete word backward", order: 30 },
  "tui.editor.deleteWordForward": { category: "Deletion", name: "Delete word forward", order: 40 },
  "tui.editor.deleteToLineStart": { category: "Deletion", name: "Delete to line start", order: 50 },
  "tui.editor.deleteToLineEnd": { category: "Deletion", name: "Delete to line end", order: 60 },

  "tui.editor.yank": { category: "Kill Ring & Clipboard", name: "Yank", order: 10 },
  "tui.editor.yankPop": { category: "Kill Ring & Clipboard", name: "Yank pop", order: 20 },
  "tui.editor.undo": { category: "Kill Ring & Clipboard", name: "Undo", order: 30 },
  "tui.input.copy": { category: "Kill Ring & Clipboard", name: "Copy selection", order: 40 },

  "app.session.new": { category: "Session", name: "Start new session", order: 10 },
  "app.session.tree": { category: "Session", name: "Open session tree", order: 20 },
  "app.session.fork": { category: "Session", name: "Fork session", order: 30 },
  "app.session.resume": { category: "Session", name: "Resume session", order: 40 },
  "app.session.togglePath": { category: "Session", name: "Toggle path display", order: 50 },
  "app.session.toggleSort": { category: "Session", name: "Toggle sort mode", order: 60 },
  "app.session.toggleNamedFilter": { category: "Session", name: "Toggle named-only filter", order: 70 },
  "app.session.rename": { category: "Session", name: "Rename session", order: 80 },
  "app.session.delete": { category: "Session", name: "Delete session", order: 90 },
  "app.session.deleteNoninvasive": { category: "Session", name: "Delete session noninvasively", order: 100 },
  "app.tree.foldOrUp": { category: "Session", name: "Fold branch or move up", order: 110 },
  "app.tree.unfoldOrDown": { category: "Session", name: "Unfold branch or move down", order: 120 },
  "app.tree.editLabel": { category: "Session", name: "Edit tree label", order: 130 },
  "app.tree.toggleLabelTimestamp": { category: "Session", name: "Toggle tree label timestamps", order: 140 },
  "app.tree.filter.default": { category: "Session", name: "Set tree filter to default", order: 150 },
  "app.tree.filter.noTools": { category: "Session", name: "Toggle tree filter no-tools", order: 160 },
  "app.tree.filter.userOnly": { category: "Session", name: "Toggle tree filter user-only", order: 170 },
  "app.tree.filter.labeledOnly": { category: "Session", name: "Toggle tree filter labeled-only", order: 180 },
  "app.tree.filter.all": { category: "Session", name: "Toggle tree filter all", order: 190 },
  "app.tree.filter.cycleForward": { category: "Session", name: "Cycle tree filter forward", order: 200 },
  "app.tree.filter.cycleBackward": { category: "Session", name: "Cycle tree filter backward", order: 210 },

  "app.model.select": { category: "Models & Thinking", name: "Open model selector", order: 10 },
  "app.model.cycleForward": { category: "Models & Thinking", name: "Cycle model forward", order: 20 },
  "app.model.cycleBackward": { category: "Models & Thinking", name: "Cycle model backward", order: 30 },
  "app.thinking.cycle": { category: "Models & Thinking", name: "Cycle thinking level", order: 40 },
  "app.thinking.toggle": { category: "Models & Thinking", name: "Toggle thinking blocks", order: 50 },
  "app.models.save": { category: "Models & Thinking", name: "Save scoped models", order: 60 },
  "app.models.enableAll": { category: "Models & Thinking", name: "Enable all scoped models", order: 70 },
  "app.models.clearAll": { category: "Models & Thinking", name: "Clear all scoped models", order: 80 },
  "app.models.toggleProvider": { category: "Models & Thinking", name: "Toggle scoped provider", order: 90 },
  "app.models.reorderUp": { category: "Models & Thinking", name: "Move scoped model up", order: 100 },
  "app.models.reorderDown": { category: "Models & Thinking", name: "Move scoped model down", order: 110 },

  "app.tools.expand": { category: "Display", name: "Expand or collapse tool output", order: 10 },

  "app.message.followUp": { category: "Message Queue", name: "Queue follow-up message", order: 10 },
  "app.message.dequeue": { category: "Message Queue", name: "Restore queued messages", order: 20 },
};
